FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
 python3.12.1 \ 
 python3-pip \
 git 

RUN pip3 install PyYAML

COPY feeding.py /usr/bin/feeding.py

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]